version: "3.9"

services:
  maker-checker:
    build: .
    container_name: maker-checker-container
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
      - mongodb
    restart: on-failure

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
